name: Fish'app
description: Application de découverte de poissons.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/poissons.json
    - assets/images/poisson_ange_imperial.jpg
    - assets/images/poisson_ange_royal.jpg
    - assets/images/poisson_betta.jpg
    - assets/images/poisson_discus.jpg
    - assets/images/poisson_licorne_bleu.jpg
    - assets/images/poisson_mandarin.jpg
    - assets/images/poisson_papillon_a_bandes.jpg
    - assets/images/poisson_perroquet_royal.jpg